<?php

namespace BooksBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccountL2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountL2Repository extends EntityRepository
{
}
