<?php

namespace BooksBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GlossTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlossTypeRepository extends EntityRepository
{
}
